"""OAuth presentation + quiet browser launch, including Windows browsers from WSL."""
from __future__ import annotations
import base64
import os
import platform
import shutil
import subprocess
import sys
import urllib.parse

from terminal_ui import safe_text


def is_wsl():
    return bool(os.environ.get('WSL_DISTRO_NAME') or 'microsoft' in platform.release().lower())


def open_browser(url):
    """Return the launcher name or None; never invoke a shell or emit gio errors."""
    parsed = urllib.parse.urlsplit(url)
    if parsed.scheme != 'https' or not parsed.hostname or parsed.username or parsed.password:
        raise ValueError('browser login requires a valid HTTPS URL')
    commands = []
    if is_wsl():
        executable = shutil.which('powershell.exe')
        if executable:
            # URL is DATA decoded inside PS, never interpolated as executable syntax.
            data = base64.b64encode(url.encode()).decode()
            script = "$u=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('"+data+"')); Start-Process -FilePath $u -ErrorAction Stop"
            encoded = base64.b64encode(script.encode('utf-16le')).decode()
            commands.append(('Windows browser', [executable,'-NoProfile','-NonInteractive','-EncodedCommand',encoded]))
        view = shutil.which('wslview')
        if view: commands.append(('Windows browser', [view,url]))
        # Do not fall through to gio/xdg-open in WSL: that's the broken path.
    elif os.name == 'nt':
        try:
            os.startfile(url)
            return 'Windows browser'
        except OSError:
            return None
    elif sys.platform == 'darwin':
        commands.append(('system browser',['open',url]))
    elif os.environ.get('DISPLAY') or os.environ.get('WAYLAND_DISPLAY'):
        executable = shutil.which('xdg-open')
        if executable: commands.append(('system browser',[executable,url]))
    for name, args in commands:
        try:
            result = subprocess.run(args, stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL, timeout=8,
                cwd='/mnt/c/Windows' if is_wsl() and os.path.isdir('/mnt/c/Windows') else None)
            if result.returncode == 0: return name
        except (OSError, subprocess.TimeoutExpired):
            pass
    return None


class AuthUI:
    def __init__(self, theme=None, color='auto', print_url=False, theme_name=None):
        if theme is None:
            import models
            from uarchat import Theme
            config = models.load_env()
            color = os.environ.get('UACHAT_COLOR') or config.get('UACHAT_COLOR') or color if color == 'auto' else color
            enabled = color == 'always' or (color == 'auto' and sys.stdout.isatty() and not os.environ.get('NO_COLOR'))
            theme = Theme(theme_name or os.environ.get('UACHAT_THEME') or config.get('UACHAT_THEME') or 'midnight',enabled)
        elif color != 'auto' or theme_name:
            theme = type(theme)(theme_name or theme.name, theme.enabled if color == 'auto' else color == 'always')
        self.theme = theme
        self.print_url = print_url

    def line(self, text, style='dim'):
        print(self.theme.paint('  '+safe_text(text),style),flush=True)

    def title(self,text):
        print('\n'+self.theme.paint('  '+safe_text(text),'title','1'),flush=True)

    def link(self,url,label):
        # Deliberate OSC8 only from a trusted URL generated by the OAuth flow.
        if sys.stdout.isatty() and os.environ.get('TERM') != 'dumb':
            painted = self.theme.paint(label,'accent','4')
            print('  \x1b]8;;'+url+'\x1b\\'+painted+'\x1b]8;;\x1b\\',flush=True)
        else:
            self.line(url,'accent')

    def browser(self,url,provider):
        self.title(provider+' · вход через браузер')
        launched = open_browser(url)
        if launched:
            self.line('Браузер запущен: '+launched+'.','ok')
            self.link(url,'Открыть страницу входа повторно')
            if self.print_url: self.line(url,'accent')
        else:
            self.line('Не удалось открыть браузер автоматически.','warn')
            self.line('Открой эту ссылку вручную на этом компьютере:')
            self.line(url,'accent')
            self.line('Для SSH/удалённой машины используй login --headless.','warn')
        self.line('Ожидаю авторизацию · Ctrl-C отменяет вход.')
        return launched

    def device(self,url,code):
        self.title('Codex · вход на другой машине / headless')
        self.line('1. Открой страницу в любом браузере:')
        self.link(url,'chatgpt / codex · device login')
        self.line('2. Введи одноразовый код:')
        self.line(code,'accent')
        self.line('Код действует до 15 минут · Ctrl-C отменяет вход.')
        self.line('Продолжай только если ты сам начал этот вход.','warn')
