#!/usr/bin/env python3
"""Write the uachat env file with the OpenCode Go key from the omp credential store.

The store is located in this order: $UACHAT_OMP_DB, ~/.omp/agent/agent.db, then
/mnt/c/Users/*/.omp/agent/agent.db (omp running on Windows).
The database is read through a temporary copy: WAL-mode SQLite on a Windows
filesystem is not reliably readable from WSL through /mnt/c.
"""
from __future__ import annotations

import glob
import json
import os
import shutil
import sqlite3
import tempfile

OUT = os.path.expanduser("~/.config/uachat/env")
PROVIDER = "opencode-go"


def find_source() -> str:
    override = os.environ.get("UACHAT_OMP_DB")
    if override:
        if not os.path.exists(override):
            raise SystemExit(f"UACHAT_OMP_DB points at a missing file: {override}")
        return override
    native = os.path.expanduser("~/.omp/agent/agent.db")
    if os.path.exists(native):
        return native
    for candidate in sorted(glob.glob("/mnt/c/Users/*/.omp/agent/agent.db")):
        return candidate
    raise SystemExit("could not find the omp credential store; set UACHAT_OMP_DB to agent.db")


def read_key(source: str) -> str:
    with tempfile.TemporaryDirectory() as work:
        target = os.path.join(work, "agent.db")
        for suffix in ("", "-wal", "-shm"):
            try:
                shutil.copyfile(source + suffix, target + suffix)
            except OSError:
                continue
        connection = sqlite3.connect(target)
        row = connection.execute(
            "select data from auth_credentials where provider = ? and credential_type = ? "
            "order by updated_at desc limit 1",
            (PROVIDER, "api_key"),
        ).fetchone()
        connection.close()
    if row is None:
        raise SystemExit(f"no {PROVIDER} api_key credential in {source}")
    return json.loads(row[0])["key"]


def main() -> int:
    source = find_source()
    key = read_key(source)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write(f"# generated by uachat/extract-key.py from {source}\n")
        handle.write("UNREAL_HARNESS_LLM_MODEL=deepseek-v4.1-flash\n")
        handle.write("UNREAL_HARNESS_LLM_MAX_ATTEMPTS=3\n")
        handle.write("UACHAT_THINKING=max\n")
        handle.write("UACHAT_BRIDGE_TARGET=https://opencode.ai/zen/go/v1\n")
        handle.write(f"UACHAT_BRIDGE_KEY={key}\n")
    os.chmod(OUT, 0o600)
    print(f"wrote {OUT} from {source}: key prefix {key[:8]}…, length {len(key)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
